// <auto-generated />
using System;
using DeskFlowApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskFlowApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeskFlowApi.Models.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(75)")
                        .HasColumnName("nomeCat");

                    b.HasKey("CategoriaId");

                    b.ToTable("tb_categorias", (string)null);
                });

            modelBuilder.Entity("DeskFlowApi.Models.Entities.Chamado", b =>
                {
                    b.Property<int>("ChamadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChamadoId"));

                    b.Property<int>("CategoriaIdFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAbertura")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataFechamento");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("prioridade");

                    b.Property<string>("SolicitanteNome")
                        .IsRequired()
                        .HasColumnType("varchar(75)")
                        .HasColumnName("solicitanteNome");

                    b.Property<string>("Solucao")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("solucao");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("aberto")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("ChamadoId");

                    b.HasIndex("CategoriaIdFK");

                    b.ToTable("tb_chamados", (string)null);
                });

            modelBuilder.Entity("DeskFlowApi.Models.Entities.Interacao", b =>
                {
                    b.Property<int>("InteracaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("interacoesId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteracaoId"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("autor");

                    b.Property<int>("ChamadoIdFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataRegistro");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("mensagem");

                    b.HasKey("InteracaoId");

                    b.HasIndex("ChamadoIdFK");

                    b.ToTable("tb_interacoes", (string)null);
                });

            modelBuilder.Entity("DeskFlowApi.Models.Entities.Chamado", b =>
                {
                    b.HasOne("DeskFlowApi.Models.Entities.Categoria", "Categoria")
                        .WithMany("ChamadosList")
                        .HasForeignKey("CategoriaIdFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("DeskFlowApi.Models.Entities.Interacao", b =>
                {
                    b.HasOne("DeskFlowApi.Models.Entities.Chamado", "Chamado")
                        .WithMany("InteracoesList")
                        .HasForeignKey("ChamadoIdFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("DeskFlowApi.Models.Entities.Categoria", b =>
                {
                    b.Navigation("ChamadosList");
                });

            modelBuilder.Entity("DeskFlowApi.Models.Entities.Chamado", b =>
                {
                    b.Navigation("InteracoesList");
                });
#pragma warning restore 612, 618
        }
    }
}
